# Funding

github: 
patreon: Kami_YT
open_collective: # Replace with a single Open Collective username
ko_fi: kamiyt
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: senpaihunters
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['buymeacoffee.com/KamiAMVS', 'https://www.youtube.com/@Kami_YT', 'https://github.com/SenpaiHunters/SpotOn']
